# Generated by Django 5.1.7 on 2026-06-04 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['date'], name='core_pagevi_date_333de3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session_key'], name='core_pagevi_session_ec8556_idx'),
        ),
    ]
