# Generated by Django 5.1.7 on 2026-06-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_url_alter_profile_avatar'),
        ('notes', '0006_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_subjects',
            field=models.ManyToManyField(blank=True, related_name='followers', to='notes.subject'),
        ),
    ]
