# Generated by Django 5.1.7 on 2026-06-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_followed_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
