# Generated by Django 4.2.30 on 2026-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_post_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='posts/files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
