# Generated by Django 4.2.30 on 2026-06-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_post_extracted_text_post_file_post_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='notes.note'),
        ),
    ]
