# Generated by Django 4.2.30 on 2026-06-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_post_shared_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='notes.subject'),
        ),
    ]
