# Generated by Django 4.2.30 on 2026-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='question_count',
            field=models.IntegerField(default=10, help_text='Number of questions to include'),
        ),
    ]
